export const DEFAULT_RECEIPT_SETTINGS = {
  printMode: 'auto',
  printerProfile: {
    profileName: 'Front Counter',
    paperWidth: '80mm',
    saleAdapter: 'browser',
    testingAdapter: 'fake',
    previewAdapter: 'preview',
    copies: 1,
    simulateFailure: false,
  },
  reprintPolicy: {
    windowMinutes: 20,
    maxManualReprints: 2,
    adminOverrideAfterWindow: false,
    adminOverrideRoles: ['admin'],
  },
  labels: {
    reprint: 'REPRINT',
    voided: 'VOIDED',
    preOrder: 'PRE-ORDER',
  },
  testing: {
    fakeModeEnabled: true,
    previewEnabled: true,
    pdfEnabled: true,
  },
};

export const DEFAULT_TEMPLATE_SCHEMA = {
  stylePreset: 'classic_thermal',
  separatorStyle: 'solid',
  paperWidth: '80mm',
  typography: {
    headerAlignment: 'center',
    bodyAlignment: 'left',
    footerAlignment: 'center',
    compactSpacing: false,
    boldTotal: true,
    fontFamily: 'courier',
    baseFontSize: 12,
    businessNameFontSize: 19,
    metaFontSize: 12,
    lineHeight: 1.35,
  },
  sections: {
    header: {
      businessName: 'Sina Sweet',
      branchName: '',
      slogan: '',
      address: '',
      phone: '',
      taxId: '',
      website: '',
      storeCode: '',
      deviceLabel: '',
      cashierLabel: 'Cashier',
      showLogo: false,
      logoUrl: '',
    },
    transaction: {
      showReceiptNumber: true,
      showDateTime: true,
      showCashier: true,
      showPaymentMethod: true,
      showCustomerInfo: true,
      showInternalRef: true,
      showNotes: true,
      dateTimeFormat: 'locale',
      currencyCode: 'ETB',
      decimals: 2,
    },
    items: {
      showSku: false,
      showUnitPrice: true,
      showSubtotal: true,
      showModifiers: true,
      wrapNames: true,
      quantityLabel: 'QTY',
      priceLabel: 'PRICE',
      totalLabel: 'TOTAL',
      columnGap: 12,
      quantityColumnWidth: 48,
      totalColumnWidth: 96,
    },
    totals: {
      showSubtotal: true,
      showTax: true,
      showDiscounts: true,
      showServiceCharge: true,
      showPaidAmount: true,
      showChange: true,
      showBalanceDue: true,
      totalLabel: 'TOTAL',
      paidLabel: 'PAID',
      changeLabel: 'CHANGE',
      balanceLabel: 'BALANCE',
    },
    footer: {
      footerText: 'Thank you for shopping with us.',
      legalText: '',
      showQr: false,
      qrValue: '',
    },
  },
  sectionOrder: ['header', 'transaction', 'items', 'totals', 'footer'],
};

export const RECEIPT_STYLE_PRESETS = [
  { value: 'classic_thermal', label: 'Classic thermal' },
  { value: 'minimal', label: 'Minimal' },
  { value: 'bold_total', label: 'Bold total' },
  { value: 'dotted', label: 'Dotted separators' },
  { value: 'solid', label: 'Solid separators' },
];
