extends:
  - eslint:recommended

env:
  node: true
  es2022: true

parserOptions:
  ecmaVersion: 2022
  sourceType: module

rules:
  no-console: warn
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  no-var: error
  prefer-const: error
  eqeqeq:
    - error
    - always
  curly:
    - error
    - all
  no-throw-literal: error
  prefer-promise-reject-errors: error
