import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    appTitle: 'Sina Sweet',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    username: 'Username',
    password: 'Password',
    branch: 'Location',
    dashboard: 'Dashboard',
    products: 'Products Management',
    addProduct: 'Add Product',
    newSale: 'New Sale',
    cartEmpty: 'Cart is empty',
    completeSale: 'Complete Sale',
    queueSaleOffline: 'Queue Sale (Offline)',
    processing: 'Processing...',
    inventory: 'Inventory',
    sales: 'Sales',
    expenses: 'Expenses',
    staffPayments: 'Staff Payments',
    reports: 'Reports',
    notifications: 'Notifications',
    syncQueue: 'Sync Queue',
    staffManagement: 'Staff Management',
    historyLifecycle: 'History Lifecycle',
    accountManagement: 'Account Management',
    batches: 'Batches',
    logout: 'Logout',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    salesHistory: 'Sales History',
    startDate: 'Start Date',
    endDate: 'End Date',
    specificDayExact: 'Specific Day (exact)',
    search: 'Search',
    receiptOrAmount: 'Receipt # or Amount',
    receipt: 'Receipt #',
    dateTime: 'Date & Time',
    amount: 'Amount',
    cashier: 'Cashier',
    payment: 'Payment',
    status: 'Status',
    voidDetails: 'Void Details',
    sync: 'Sync',
    actions: 'Actions',
    noSalesFound: 'No sales found',
    unknown: 'Unknown',
    cancelled: 'Cancelled',
    completed: 'Completed',
    noReasonProvided: 'No reason provided',
    offline: 'Offline',
    online: 'Online',
    view: 'View',
    void: 'Void',
    transactionInfo: 'Transaction Info',
    items: 'Items',
    product: 'Product',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    voidThisSale: 'Void This Sale?',
    reasonForVoiding: 'Reason for voiding *',
    close: 'Close',
    processFailedLoadSalesHistory: 'Failed to load sales history',
    provideVoidReason: 'Please provide a reason for voiding this sale',
    failedVoidSale: 'Failed to void sale',
    processingShort: 'Processing...',
    voidSaleRestoreInventory: 'Void Sale & Restore Inventory',
    voidRemainingSuffix: 'to void',
    reasonPlaceholder: 'e.g., Customer changed their mind, entered wrong amount...',
    voided: 'VOIDED',
    paymentMethod: 'Payment Method',
    dateAndTimeLabel: 'Date & Time:',
    amountLabel: 'Amount:',
    cashierLabel: 'Cashier:',
    paymentMethodLabel: 'Payment Method:',
    voidedAt: 'Voided at:',
    reason: 'Reason:',
    inventoryRestoredMessage: 'Inventory will be restored automatically.',
    remainingToVoidPrefix: 'You have',
    remainingToVoidMiddle: 'minutes remaining to void this sale.',
    saleVoidedMessage: 'has been voided. Inventory restored.',
    orders: 'Orders',
    ordersQueue: 'Orders Queue',
    preOrders: 'Pre-Orders',
    welcomeBack: 'Welcome back — sign in to continue.',
    forgotAdminPassword: 'Forgot admin password?',
    recoverAdminPassword: 'Recover Admin Password',
    adminUsername: 'Admin Username',
    recoveryKey: 'Recovery Key',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resetting: 'Resetting...',
    resetPassword: 'Reset Password',
    closeModal: 'Close',
    recoveryHelp: 'If you are not an admin, contact your system administrator to reset your password. If you are an admin and forgot your password, contact the technical team to request the secure recovery key.',
    pendingOfflineActions: 'Pending Offline Actions',
    pendingOfflineDetails: 'You have offline action(s) pending. These will be forwarded to admin for syncing when online.',
    cancel: 'Cancel',
    logoutAnyway: 'Logout Anyway',
    fillAllRecoveryFields: 'Fill all recovery fields.',
    passwordMismatch: 'New password and confirmation do not match.',
    adminPasswordResetSuccess: 'Admin password reset successfully. You can login now.',
    recoveryDisabled: 'Recovery is disabled on this server. Ask owner to set ADMIN_RECOVERY_KEY.',
    hideArchived: 'Hide Archived',
    seeArchivedProducts: 'See Archived Products',
    addProductGroup: 'Add Product Group',
    searchProducts: 'Search Products',
    searchGroupsOrVariants: 'Search groups or variants...',
    addCategory: 'Add Category',
    categoryAdded: 'Category added.',
    deleteVariantConfirm: 'Delete this variant? If not deletable it will be archived.',
    passwordPolicyHint: 'Password must be 8+ chars with letter, number, and special character.',
    confirm: 'Confirm',
    confirmAction: 'Are you sure you want to continue?',
    // Nav extras
    ordersNav: 'Orders',
    // Dashboard
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    periodLabel: 'Period',
    // Inventory
    inventoryManagement: 'Inventory Management',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    totalItems: 'Total Items',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    searchInventory: 'Search inventory by product...',
    productVariant: 'Variant',
    quantity: 'Quantity',
    lastUpdated: 'Last Updated',
    source: 'Source',
    selectProduct: 'Select Product Variant',
    productCannotChange: 'Product cannot be changed when editing. Only quantity is editable.',
    pendingSync: 'Pending Sync',
    archived: 'Archived',
    // Products
    id: 'ID',
    category: 'Category',
    unit: 'Unit',
    cost: 'Cost',
    active: 'Active',
    inactive: 'Inactive',
    renameGroup: 'Rename Group',
    addVariant: 'Add Variant',
    groupName: 'Group Name',
    variantName: 'Variant Name',
    source_baked: 'Baked',
    source_purchased: 'Purchased',
    createGroup: 'Create Group',
    createProductGroup: 'Create Product Group',
    editVariant: 'Edit Variant',
    addVariantToGroup: 'Add Variant to',
    // Expenses
    expensesManagement: 'Expenses Management',
    expenseId: 'Expense ID',
    date: 'Date',
    description: 'Description',
    createdBy: 'Created By',
    editWindow: 'Edit Window',
    filterByDay: 'Filter by Day',
    clearFilter: 'Clear Filter',
    totalExpenses: 'Total Expenses',
    totalRecords: 'Total Records',
    avgExpense: 'Avg. Expense',
    addExpense: 'Add Expense',
    editExpense: 'Edit Expense',
    addNewExpense: 'Add New Expense',
    expenseDate: 'Date',
    noExpenses: 'No expenses found',
    viewDescription: 'View',
    locked: 'Locked',
    // Staff payments
    staffPaymentsPage: 'Staff Payments',
    payStaff: 'Pay Staff',
    paymentId: 'Payment ID',
    staff: 'Staff',
    paymentDate: 'Date',
    notes: 'Notes',
    totalPaid: 'Total Paid',
    dailyPaid: 'Daily Paid',
    weeklyPaid: 'Weekly Paid',
    monthlyPaid: 'Monthly Paid',
    noPayments: 'No payments match current filters.',
    workedDays: 'Worked Days',
    dailyRate: 'Daily Rate',
    suggestedAmount: 'Suggested',
    useSuggested: 'Use Suggested Amount',
    selectStaff: 'Select staff',
    payNow: 'Pay Now',
    updatePayment: 'Update Payment',
    deletePayment: 'Delete Payment',
    paymentNote: 'Payment Note',
    createPayment: 'Create Payment',
    // Notifications
    notificationsPage: 'Notifications',
    refreshNotifications: 'Refresh',
    markAllRead: 'Mark All as Read',
    allTypes: 'All Types',
    allStatuses: 'All Status',
    unread: 'Unread',
    read: 'Read',
    noNotifications: 'No notifications',
    allCaughtUp: 'All caught up! You have no',
    notificationsLabel: 'notifications',
    markAsRead: 'Mark as read',
    deleteNotification: 'Delete',
    total: 'Total',
    unreadLabel: 'Unread',
    readLabel: 'Read',
    // Account management
    activeAccounts: 'Active Accounts',
    staffWithoutAccount: 'Staff Without Account',
    myAdminCredentials: 'My Admin Credentials',
    currentPassword: 'Current Password',
    newUsername: 'New Username',
    newPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    updateCredentials: 'Update My Credentials',
    credentialsHint: 'You can update username, password, or both. Passwords must include letter, number, and special character.',
    createStaffAccount: 'Create Staff Account',
    noStaffAvailable: 'No staff members available for account creation. Add staff profiles first in Staff Management.',
    selectStaffProfile: 'Select staff profile',
    staffWithoutAccountNote: 'Staff with role "other" (bakers, cleaners, etc.) typically do not need accounts',
    usernameLabel: 'Username',
    accountRole: 'Account Role',
    createAccount: 'Create Account',
    accountDirectory: 'Account Directory',
    fullName: 'Name',
    activeAccountsTitle: 'Active Accounts',
    inactiveAccountsTitle: 'Inactive Accounts',
    noAccountsYet: 'No accounts created yet.',
    noInactiveAccounts: 'No inactive accounts.',
    editAccount: 'Edit',
    disableAccount: 'Disable',
    enableAccount: 'Enable',
    deleteAccount: 'Delete',
    confirmCredentialUpdate: 'Confirm Credential Update',
    // Sync queue
    syncQueuePage: 'Sync Queue',
    // History lifecycle
    historyLifecyclePage: 'History Lifecycle',
    // Orders
    createPreOrder: 'Create Pre-Order',
    customerName: 'Customer Name',
    phone: 'Phone',
    pickupTime: 'Pickup Time',
    amountPaidNow: 'Amount Paid Now',
    customerNote: 'Customer Note',
    customerNotePlaceholder: 'Special requests, allergy notes, delivery clues...',
    orderItems: 'Order Items',
    customItemName: 'Custom item name',
    customItemPlaceholder: 'Use for non-product items',
    unitPrice: 'Unit price',
    addItemRow: '+ Add Item Row',
    orderTotal: 'Order Total',
    paid: 'Paid',
    remaining: 'Remaining',
    myOrders: 'My Orders',
    noPreOrders: 'No pre-orders',
    orderId: 'Order ID',
    customer: 'Customer',
    prep: 'Prep',
    orderPayment: 'Payment',
    pickup: 'Pickup',
    editPreOrder: 'Edit Pre-Order',
    viewNote: 'View Note',
    customerNoteTitle: 'Customer Note',
    noNote: 'No note added for this pre-order.',
    deletePreOrder: 'Delete',
    deleteLockedLabel: 'Delete locked',
    // Sales POS
    productGroups: 'Product Groups',
    allSources: 'All Sources',
    allGroups: 'All Groups',
    allCategories: 'All Categories',
    resetFilters: 'Reset Filters',
    outOfStock: 'Out of stock',
    inStockSuffix: 'in stock',
    variantSuffix: 'variant',
    variantsSuffix: 'variants',
    selectVariant: 'Select Variant',
    cart: 'Cart',
    paymentLabel: 'Payment:',
    totalLabel: 'Total:',
    receiptTitle: 'Receipt',
    receiptNumber: 'Receipt #:',
    dateLabel: 'Date:',
    paymentMethodLabel2: 'Payment Method:',
    totalAmountLabel: 'Total:',
  },
  am: {
    appTitle: 'ሲና ስዊት',
    signIn: 'ግባ',
    signingIn: 'በመግባት ላይ...',
    username: 'የተጠቃሚ ስም',
    password: 'የይለፍ ቃል',
    branch: 'ቦታ',
    dashboard: 'ዳሽቦርድ',
    products: 'የምርት አስተዳደር',
    addProduct: 'ምርት ጨምር',
    newSale: 'አዲስ ሽያጭ',
    cartEmpty: 'ጋሪው ባዶ ነው',
    completeSale: 'ሽያጭ አጠናቅቅ',
    queueSaleOffline: 'ከመስመር ውጭ ሽያጭ አስቀምጥ',
    processing: 'በሂደት ላይ...',
    inventory: 'ኢንቨንተሪ',
    sales: 'ሽያጭ',
    expenses: 'ወጪዎች',
    staffPayments: 'የሰራተኛ ክፍያ',
    reports: 'ሪፖርቶች',
    notifications: 'ማሳወቂያዎች',
    syncQueue: 'ሲንክ ዝርዝር',
    staffManagement: 'የሰራተኛ አስተዳደር',
    historyLifecycle: 'ታሪክ ላይፍሳይክል',
    accountManagement: 'የአካውንት አስተዳደር',
    batches: 'ባች',
    logout: 'ውጣ',
    language: 'ቋንቋ',
    theme: 'ገጽታ',
    light: 'ብርሃን',
    dark: 'ጨለማ',
    salesHistory: 'የሽያጭ ታሪክ',
    startDate: 'የመጀመሪያ ቀን',
    endDate: 'የመጨረሻ ቀን',
    specificDayExact: 'የተወሰነ ቀን (ትክክለኛ)',
    search: 'ፈልግ',
    receiptOrAmount: 'ደረሰኝ ቁጥር ወይም መጠን',
    receipt: 'ደረሰኝ ቁጥር',
    dateTime: 'ቀን እና ሰዓት',
    amount: 'መጠን',
    cashier: 'ካሸር',
    payment: 'ክፍያ',
    status: 'ሁኔታ',
    voidDetails: 'የመሰረዝ ዝርዝር',
    sync: 'ሲንክ',
    actions: 'እርምጃዎች',
    noSalesFound: 'ምንም ሽያጭ አልተገኘም',
    unknown: 'ያልታወቀ',
    cancelled: 'ተሰርዟል',
    completed: 'ተጠናቋል',
    noReasonProvided: 'ምክንያት አልተሰጠም',
    offline: 'ከመስመር ውጭ',
    online: 'በመስመር ላይ',
    view: 'ይመልከቱ',
    void: 'ሰርዝ',
    transactionInfo: 'የግብይት መረጃ',
    items: 'እቃዎች',
    product: 'ምርት',
    qty: 'ብዛት',
    price: 'ዋጋ',
    total: 'ጠቅላላ',
    voidThisSale: 'ይህን ሽያጭ ሰርዝ?',
    reasonForVoiding: 'የመሰረዝ ምክንያት *',
    close: 'ዝጋ',
    processFailedLoadSalesHistory: 'የሽያጭ ታሪክ መጫን አልተቻለም',
    provideVoidReason: 'እባክዎ ይህን ሽያጭ ለመሰረዝ ምክንያት ያስገቡ',
    failedVoidSale: 'ሽያጩን መሰረዝ አልተቻለም',
    processingShort: 'በሂደት ላይ...',
    voidSaleRestoreInventory: 'ሽያጭ ሰርዝ እና ኢንቨንተሪ መልስ',
    voidRemainingSuffix: 'ለመሰረዝ',
    reasonPlaceholder: 'ምሳሌ፦ ደንበኛው ሀሳቡን ቀይሯል፣ የተሳሳተ መጠን ገብቷል...',
    voided: 'ተሰርዟል',
    paymentMethod: 'የክፍያ ዘዴ',
    dateAndTimeLabel: 'ቀን እና ሰዓት:',
    amountLabel: 'መጠን:',
    cashierLabel: 'ካሸር:',
    paymentMethodLabel: 'የክፍያ ዘዴ:',
    voidedAt: 'የተሰረዘበት ጊዜ:',
    reason: 'ምክንያት:',
    inventoryRestoredMessage: 'ኢንቨንተሪ በራስ-ሰር ይመለሳል።',
    remainingToVoidPrefix: 'እርስዎ አሁንም',
    remainingToVoidMiddle: 'ደቂቃ ቀርቶዎታል ይህን ሽያጭ ለመሰረዝ።',
    saleVoidedMessage: 'ተሰርዟል። ኢንቨንተሪ ተመልሷል።',
    orders: 'ትዕዛዞች',
    ordersQueue: 'የትዕዛዝ ወረፋ',
    preOrders: 'ቅድመ-ትዕዛዞች',
    welcomeBack: 'እንኳን ተመለሱ — ለመቀጠል ይግቡ።',
    forgotAdminPassword: 'የአድሚን የይለፍ ቃል ረሱ?',
    recoverAdminPassword: 'የአድሚን የይለፍ ቃል መመለሻ',
    adminUsername: 'የአድሚን ተጠቃሚ ስም',
    recoveryKey: 'የመመለሻ ቁልፍ',
    newPassword: 'አዲስ የይለፍ ቃል',
    confirmNewPassword: 'አዲስ የይለፍ ቃል ያረጋግጡ',
    resetting: 'በመቀየር ላይ...',
    resetPassword: 'የይለፍ ቃል ቀይር',
    closeModal: 'ዝጋ',
    recoveryHelp: 'አድሚን ካልሆኑ የይለፍ ቃል ለመቀየር የስርዓት አስተዳዳሪዎን ያነጋግሩ። አድሚን ከሆኑ እና የይለፍ ቃል ከረሱ ከቴክኒክ ቡድን የደህንነት መመለሻ ቁልፍ ይጠይቁ።',
    pendingOfflineActions: 'የተጠባበቁ ከመስመር ውጭ ተግባራት',
    pendingOfflineDetails: 'የተጠባበቁ ከመስመር ውጭ ተግባራት አሉዎት። መስመር ሲገኝ ለማስማማት ወደ አድሚን ይላካሉ።',
    cancel: 'ሰርዝ',
    logoutAnyway: 'ሆኖም ውጣ',
    fillAllRecoveryFields: 'ሁሉንም የመመለሻ መረጃዎች ይሙሉ።',
    passwordMismatch: 'አዲስ የይለፍ ቃል እና ማረጋገጫ አይመሳሰሉም።',
    adminPasswordResetSuccess: 'የአድሚን የይለፍ ቃል ተቀይሯል። አሁን መግባት ይችላሉ።',
    recoveryDisabled: 'በዚህ ሰርቨር መመለሻ ተሰናክሏል። ባለቤቱ ADMIN_RECOVERY_KEY እንዲያቀናብር ይጠይቁ።',
    hideArchived: 'የታሸጉ ደብቅ',
    seeArchivedProducts: 'የታሸጉ ምርቶች እይ',
    addProductGroup: 'የምርት ቡድን ጨምር',
    searchProducts: 'ምርቶችን ፈልግ',
    searchGroupsOrVariants: 'ቡድኖችን ወይም ቫሪያንቶችን ፈልግ...',
    addCategory: 'ምድብ ጨምር',
    categoryAdded: 'ምድብ ታክሏል።',
    deleteVariantConfirm: 'ይህን ቫሪያንት ልንሰርዝ? መሰረዝ ካልተቻለ ይታሸጋል።',
    passwordPolicyHint: 'የይለፍ ቃል 8+ ፊደላት እና ፊደል፣ ቁጥር፣ ልዩ ምልክት ይኖረው።',
    confirm: 'አረጋግጥ',
    confirmAction: 'ለመቀጠል እርግጠኛ ነዎት?',
    ordersNav: 'ትዕዛዞች',
    daily: 'ዕለታዊ',
    weekly: 'ሳምንታዊ',
    monthly: 'ወርሃዊ',
    periodLabel: 'ጊዜ',
    inventoryManagement: 'የኢንቨንተሪ አስተዳደር',
    addItem: 'እቃ ጨምር',
    editItem: 'እቃ አርትዕ',
    totalItems: 'ጠቅላላ እቃዎች',
    inStock: 'ያለ ዝርዝር',
    lowStock: 'ዝቅተኛ ዝርዝር',
    searchInventory: 'ኢንቨንተሪ ፈልግ...',
    productVariant: 'ቫሪያንት',
    quantity: 'መጠን',
    lastUpdated: 'የመጨረሻ ዝማኔ',
    source: 'ምንጭ',
    selectProduct: 'የምርት ቫሪያንት ምረጥ',
    productCannotChange: 'ምርት ሲዘምን ሊቀየር አይችልም። መጠን ብቻ ሊዘምን ይችላል።',
    pendingSync: 'ሲንክ በጥበቃ ላይ',
    archived: 'ታሽጓል',
    id: 'መለያ',
    category: 'ምድብ',
    unit: 'አሃድ',
    cost: 'ወጪ',
    active: 'ንቁ',
    inactive: 'ንቁ ያይደለ',
    renameGroup: 'ቡድን ስም ቀይር',
    addVariant: 'ቫሪያንት ጨምር',
    groupName: 'የቡድን ስም',
    variantName: 'የቫሪያንት ስም',
    source_baked: 'የተጋገረ',
    source_purchased: 'የተገዛ',
    createGroup: 'ቡድን ፍጠር',
    createProductGroup: 'የምርት ቡድን ፍጠር',
    editVariant: 'ቫሪያንት አርትዕ',
    addVariantToGroup: 'ወደ ቡድን ቫሪያንት ጨምር',
    expensesManagement: 'የወጪ አስተዳደር',
    expenseId: 'የወጪ መለያ',
    date: 'ቀን',
    description: 'መግለጫ',
    createdBy: 'የፈጠረ',
    editWindow: 'የአርትዕ ጊዜ',
    filterByDay: 'በቀን አጣራ',
    clearFilter: 'ማጣሪያ አጽዳ',
    totalExpenses: 'ጠቅላላ ወጪ',
    totalRecords: 'ጠቅላላ መዝገቦች',
    avgExpense: 'አማካይ ወጪ',
    addExpense: 'ወጪ ጨምር',
    editExpense: 'ወጪ አርትዕ',
    addNewExpense: 'አዲስ ወጪ ጨምር',
    expenseDate: 'ቀን',
    noExpenses: 'ምንም ወጪ አልተገኘም',
    viewDescription: 'ይመልከቱ',
    locked: 'ተቆልፏል',
    staffPaymentsPage: 'የሰራተኛ ክፍያ',
    payStaff: 'ሰራተኛ ክፈል',
    paymentId: 'የክፍያ መለያ',
    staff: 'ሰራተኛ',
    paymentDate: 'ቀን',
    notes: 'ማስታወሻ',
    totalPaid: 'ጠቅላላ ክፍያ',
    dailyPaid: 'ዕለታዊ ክፍያ',
    weeklyPaid: 'ሳምንታዊ ክፍያ',
    monthlyPaid: 'ወርሃዊ ክፍያ',
    noPayments: 'ምንም ክፍያ አልተገኘም።',
    workedDays: 'የሰሩ ቀናት',
    dailyRate: 'ዕለታዊ ተመን',
    suggestedAmount: 'የሚጠቆም',
    useSuggested: 'የሚጠቆም መጠን ተጠቀም',
    selectStaff: 'ሰራተኛ ምረጥ',
    payNow: 'አሁን ክፈል',
    updatePayment: 'ክፍያ ዘምን',
    deletePayment: 'ክፍያ ሰርዝ',
    paymentNote: 'የክፍያ ማስታወሻ',
    createPayment: 'ክፍያ ፍጠር',
    notificationsPage: 'ማሳወቂያዎች',
    refreshNotifications: 'አድስ',
    markAllRead: 'ሁሉንም እንዳነበቡ ምልክት አድርግ',
    allTypes: 'ሁሉም ዓይነቶች',
    allStatuses: 'ሁሉም ሁኔታዎች',
    unread: 'ያልተነበቡ',
    read: 'የተነበቡ',
    noNotifications: 'ምንም ማሳወቂያ የለም',
    allCaughtUp: 'ሁሉም ተጠናቋል! ምንም',
    notificationsLabel: 'ማሳወቂያ የለም',
    markAsRead: 'እንዳነበቡ ምልክት አድርግ',
    deleteNotification: 'ሰርዝ',
    total: 'ጠቅላላ',
    unreadLabel: 'ያልተነበቡ',
    readLabel: 'የተነበቡ',
    activeAccounts: 'ንቁ አካውንቶች',
    staffWithoutAccount: 'አካውንት የሌላቸው ሰራተኞች',
    myAdminCredentials: 'የእኔ አድሚን ምስክርነቶች',
    currentPassword: 'የአሁኑ የይለፍ ቃል',
    newUsername: 'አዲስ ተጠቃሚ ስም',
    newPasswordLabel: 'አዲስ የይለፍ ቃል',
    confirmNewPasswordLabel: 'አዲስ የይለፍ ቃል አረጋግጥ',
    updateCredentials: 'ምስክርነቶቼን ዘምን',
    credentialsHint: 'ተጠቃሚ ስም፣ የይለፍ ቃል ወይም ሁለቱም ሊዘምኑ ይችላሉ። ፊደል፣ ቁጥር እና ልዩ ምልክት ያካትቱ።',
    createStaffAccount: 'የሰራተኛ አካውንት ፍጠር',
    noStaffAvailable: 'ለአካውንት ፈጠራ ዝግጁ ሰራተኛ የለም። ሰራተኞችን ጨምር።',
    selectStaffProfile: 'የሰራተኛ ፕሮፋይል ምረጥ',
    staffWithoutAccountNote: 'ሌሎች ሰራተኞች (አብሳዮች፣ ጽዳት ሠራተኞች) አካውንት አያስፈልጋቸውም',
    usernameLabel: 'ተጠቃሚ ስም',
    accountRole: 'የአካውንት ሚና',
    createAccount: 'አካውንት ፍጠር',
    accountDirectory: 'የአካውንት ዝርዝር',
    fullName: 'ሙሉ ስም',
    activeAccountsTitle: 'ንቁ አካውንቶች',
    inactiveAccountsTitle: 'ንቁ ያልሆኑ አካውንቶች',
    noAccountsYet: 'ምንም አካውንት አልተፈጠረም።',
    noInactiveAccounts: 'ንቁ ያልሆኑ አካውንቶች የሉም።',
    editAccount: 'አርትዕ',
    disableAccount: 'አሰናክል',
    enableAccount: 'አንቃ',
    deleteAccount: 'ሰርዝ',
    confirmCredentialUpdate: 'ምስክርነት ዝማኔ አረጋግጥ',
    syncQueuePage: 'የሲንክ ወረፋ',
    historyLifecyclePage: 'ታሪክ ዑደት',
    createPreOrder: 'ቅድመ-ትዕዛዝ ፍጠር',
    customerName: 'የደንበኛ ስም',
    phone: 'ስልክ',
    pickupTime: 'የመቀበያ ጊዜ',
    amountPaidNow: 'አሁን የተከፈለ መጠን',
    customerNote: 'የደንበኛ ማስታወሻ',
    customerNotePlaceholder: 'ልዩ ጥያቄዎች፣ አለርጂ ማስታወሻዎች...',
    orderItems: 'የትዕዛዝ እቃዎች',
    customItemName: 'ብጁ እቃ ስም',
    customItemPlaceholder: 'ለምርት ያልሆኑ እቃዎች ይጠቀሙ',
    unitPrice: 'አሃዳዊ ዋጋ',
    addItemRow: '+ ረድፍ ጨምር',
    orderTotal: 'ጠቅላላ ትዕዛዝ',
    paid: 'ተከፍሏል',
    remaining: 'ቀሪ',
    myOrders: 'ትዕዛዞቼ',
    noPreOrders: 'ቅድመ-ትዕዛዞች የሉም',
    orderId: 'የትዕዛዝ መለያ',
    customer: 'ደንበኛ',
    prep: 'ዝግጅት',
    orderPayment: 'ክፍያ',
    pickup: 'መቀበያ',
    editPreOrder: 'ቅድመ-ትዕዛዝ አርትዕ',
    viewNote: 'ማስታወሻ ይመልከቱ',
    customerNoteTitle: 'የደንበኛ ማስታወሻ',
    noNote: 'ለዚህ ቅድመ-ትዕዛዝ ምንም ማስታወሻ የለም።',
    deletePreOrder: 'ሰርዝ',
    deleteLockedLabel: 'ሰርዝ ተቆልፏል',
    productGroups: 'የምርት ቡድኖች',
    allSources: 'ሁሉም ምንጮች',
    allGroups: 'ሁሉም ቡድኖች',
    allCategories: 'ሁሉም ምድቦች',
    resetFilters: 'ማጣሪያዎች ዳግም አስጀምር',
    outOfStock: 'ዝርዝር ተጠናቋል',
    inStockSuffix: 'አለ',
    variantSuffix: 'ቫሪያንት',
    variantsSuffix: 'ቫሪያንቶች',
    selectVariant: 'ቫሪያንት ምረጥ',
    cart: 'ጋሪ',
    paymentLabel: 'ክፍያ:',
    totalLabel: 'ጠቅላላ:',
    receiptTitle: 'ደረሰኝ',
    receiptNumber: 'ደረሰኝ #:',
    dateLabel: 'ቀን:',
    paymentMethodLabel2: 'የክፍያ ዘዴ:',
    totalAmountLabel: 'ጠቅላላ:',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  const setLang = (lang) => {
    setLanguage(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const value = useMemo(() => ({ language, setLang, t }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
