import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    appTitle: 'Sina Sweet',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    username: 'Username',
    password: 'Password',
    branch: 'Location',
    dashboard: 'Dashboard',
    products: 'Products Management',
    addProduct: 'Add Product',
    newSale: 'New Sale',
    cartEmpty: 'Cart is empty',
    completeSale: 'Complete Sale',
    queueSaleOffline: 'Queue Sale (Offline)',
    processing: 'Processing...',
    inventory: 'Inventory',
    sales: 'Sales',
    expenses: 'Expenses',
    staffPayments: 'Staff Payments',
    reports: 'Reports',
    notifications: 'Notifications',
    syncQueue: 'Sync Queue',
    staffManagement: 'Staff Management',
    historyLifecycle: 'History Lifecycle',
    accountManagement: 'Account Management',
    batches: 'Batches',
    logout: 'Logout',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    salesHistory: 'Sales History',
    startDate: 'Start Date',
    endDate: 'End Date',
    specificDayExact: 'Specific Day (exact)',
    search: 'Search',
    receiptOrAmount: 'Receipt # or Amount',
    receipt: 'Receipt #',
    dateTime: 'Date & Time',
    amount: 'Amount',
    cashier: 'Cashier',
    payment: 'Payment',
    status: 'Status',
    voidDetails: 'Void Details',
    sync: 'Sync',
    actions: 'Actions',
    noSalesFound: 'No sales found',
    unknown: 'Unknown',
    cancelled: 'Cancelled',
    completed: 'Completed',
    noReasonProvided: 'No reason provided',
    offline: 'Offline',
    online: 'Online',
    view: 'View',
    void: 'Void',
    transactionInfo: 'Transaction Info',
    items: 'Items',
    product: 'Product',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    voidThisSale: 'Void This Sale?',
    reasonForVoiding: 'Reason for voiding *',
    close: 'Close',
    processFailedLoadSalesHistory: 'Failed to load sales history',
    provideVoidReason: 'Please provide a reason for voiding this sale',
    failedVoidSale: 'Failed to void sale',
    processingShort: 'Processing...',
    voidSaleRestoreInventory: 'Void Sale & Restore Inventory',
    voidRemainingSuffix: 'to void',
    reasonPlaceholder: 'e.g., Customer changed their mind, entered wrong amount...',
    voided: 'VOIDED',
    paymentMethod: 'Payment Method',
    dateAndTimeLabel: 'Date & Time:',
    amountLabel: 'Amount:',
    cashierLabel: 'Cashier:',
    paymentMethodLabel: 'Payment Method:',
    voidedAt: 'Voided at:',
    reason: 'Reason:',
    inventoryRestoredMessage: 'Inventory will be restored automatically.',
    remainingToVoidPrefix: 'You have',
    remainingToVoidMiddle: 'minutes remaining to void this sale.',
    saleVoidedMessage: 'has been voided. Inventory restored.',
    orders: 'Orders',
    ordersQueue: 'Orders Queue',
    preOrders: 'Pre-Orders',
    welcomeBack: 'Welcome back — sign in to continue.',
    forgotAdminPassword: 'Forgot admin password?',
    recoverAdminPassword: 'Recover Admin Password',
    adminUsername: 'Admin Username',
    recoveryKey: 'Recovery Key',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resetting: 'Resetting...',
    resetPassword: 'Reset Password',
    closeModal: 'Close',
    recoveryHelp: 'If you are not an admin, contact your system administrator to reset your password. If you are an admin and forgot your password, contact the technical team to request the secure recovery key.',
    pendingOfflineActions: 'Pending Offline Actions',
    pendingOfflineDetails: 'You have offline action(s) pending. These will be forwarded to admin for syncing when online.',
    cancel: 'Cancel',
    logoutAnyway: 'Logout Anyway',
    fillAllRecoveryFields: 'Fill all recovery fields.',
    passwordMismatch: 'New password and confirmation do not match.',
    adminPasswordResetSuccess: 'Admin password reset successfully. You can login now.',
    recoveryDisabled: 'Recovery is disabled on this server. Ask owner to set ADMIN_RECOVERY_KEY.',
    hideArchived: 'Hide Archived',
    seeArchivedProducts: 'See Archived Products',
    addProductGroup: 'Add Product Group',
    searchProducts: 'Search Products',
    searchGroupsOrVariants: 'Search groups or variants...',
    addCategory: 'Add Category',
    categoryAdded: 'Category added.',
    deleteVariantConfirm: 'Delete this variant? If not deletable it will be archived.',
    passwordPolicyHint: 'Password must be 8+ chars with letter, number, and special character.',
    confirm: 'Confirm',
    confirmAction: 'Are you sure you want to continue?',
  },
  am: {
    appTitle: 'ሲና ስዊት',
    signIn: 'ግባ',
    signingIn: 'በመግባት ላይ...',
    username: 'የተጠቃሚ ስም',
    password: 'የይለፍ ቃል',
    branch: 'ቦታ',
    dashboard: 'ዳሽቦርድ',
    products: 'የምርት አስተዳደር',
    addProduct: 'ምርት ጨምር',
    newSale: 'አዲስ ሽያጭ',
    cartEmpty: 'ጋሪው ባዶ ነው',
    completeSale: 'ሽያጭ አጠናቅቅ',
    queueSaleOffline: 'ከመስመር ውጭ ሽያጭ አስቀምጥ',
    processing: 'በሂደት ላይ...',
    inventory: 'ኢንቨንተሪ',
    sales: 'ሽያጭ',
    expenses: 'ወጪዎች',
    staffPayments: 'የሰራተኛ ክፍያ',
    reports: 'ሪፖርቶች',
    notifications: 'ማሳወቂያዎች',
    syncQueue: 'ሲንክ ዝርዝር',
    staffManagement: 'የሰራተኛ አስተዳደር',
    historyLifecycle: 'ታሪክ ላይፍሳይክል',
    accountManagement: 'የአካውንት አስተዳደር',
    batches: 'ባች',
    logout: 'ውጣ',
    language: 'ቋንቋ',
    theme: 'ገጽታ',
    light: 'ብርሃን',
    dark: 'ጨለማ',
    salesHistory: 'የሽያጭ ታሪክ',
    startDate: 'የመጀመሪያ ቀን',
    endDate: 'የመጨረሻ ቀን',
    specificDayExact: 'የተወሰነ ቀን (ትክክለኛ)',
    search: 'ፈልግ',
    receiptOrAmount: 'ደረሰኝ ቁጥር ወይም መጠን',
    receipt: 'ደረሰኝ ቁጥር',
    dateTime: 'ቀን እና ሰዓት',
    amount: 'መጠን',
    cashier: 'ካሸር',
    payment: 'ክፍያ',
    status: 'ሁኔታ',
    voidDetails: 'የመሰረዝ ዝርዝር',
    sync: 'ሲንክ',
    actions: 'እርምጃዎች',
    noSalesFound: 'ምንም ሽያጭ አልተገኘም',
    unknown: 'ያልታወቀ',
    cancelled: 'ተሰርዟል',
    completed: 'ተጠናቋል',
    noReasonProvided: 'ምክንያት አልተሰጠም',
    offline: 'ከመስመር ውጭ',
    online: 'በመስመር ላይ',
    view: 'ይመልከቱ',
    void: 'ሰርዝ',
    transactionInfo: 'የግብይት መረጃ',
    items: 'እቃዎች',
    product: 'ምርት',
    qty: 'ብዛት',
    price: 'ዋጋ',
    total: 'ጠቅላላ',
    voidThisSale: 'ይህን ሽያጭ ሰርዝ?',
    reasonForVoiding: 'የመሰረዝ ምክንያት *',
    close: 'ዝጋ',
    processFailedLoadSalesHistory: 'የሽያጭ ታሪክ መጫን አልተቻለም',
    provideVoidReason: 'እባክዎ ይህን ሽያጭ ለመሰረዝ ምክንያት ያስገቡ',
    failedVoidSale: 'ሽያጩን መሰረዝ አልተቻለም',
    processingShort: 'በሂደት ላይ...',
    voidSaleRestoreInventory: 'ሽያጭ ሰርዝ እና ኢንቨንተሪ መልስ',
    voidRemainingSuffix: 'ለመሰረዝ',
    reasonPlaceholder: 'ምሳሌ፦ ደንበኛው ሀሳቡን ቀይሯል፣ የተሳሳተ መጠን ገብቷል...',
    voided: 'ተሰርዟል',
    paymentMethod: 'የክፍያ ዘዴ',
    dateAndTimeLabel: 'ቀን እና ሰዓት:',
    amountLabel: 'መጠን:',
    cashierLabel: 'ካሸር:',
    paymentMethodLabel: 'የክፍያ ዘዴ:',
    voidedAt: 'የተሰረዘበት ጊዜ:',
    reason: 'ምክንያት:',
    inventoryRestoredMessage: 'ኢንቨንተሪ በራስ-ሰር ይመለሳል።',
    remainingToVoidPrefix: 'እርስዎ አሁንም',
    remainingToVoidMiddle: 'ደቂቃ ቀርቶዎታል ይህን ሽያጭ ለመሰረዝ።',
    saleVoidedMessage: 'ተሰርዟል። ኢንቨንተሪ ተመልሷል።',
    orders: 'ትዕዛዞች',
    ordersQueue: 'የትዕዛዝ ወረፋ',
    preOrders: 'ቅድመ-ትዕዛዞች',
    welcomeBack: 'እንኳን ተመለሱ — ለመቀጠል ይግቡ።',
    forgotAdminPassword: 'የአድሚን የይለፍ ቃል ረሱ?',
    recoverAdminPassword: 'የአድሚን የይለፍ ቃል መመለሻ',
    adminUsername: 'የአድሚን ተጠቃሚ ስም',
    recoveryKey: 'የመመለሻ ቁልፍ',
    newPassword: 'አዲስ የይለፍ ቃል',
    confirmNewPassword: 'አዲስ የይለፍ ቃል ያረጋግጡ',
    resetting: 'በመቀየር ላይ...',
    resetPassword: 'የይለፍ ቃል ቀይር',
    closeModal: 'ዝጋ',
    recoveryHelp: 'አድሚን ካልሆኑ የይለፍ ቃል ለመቀየር የስርዓት አስተዳዳሪዎን ያነጋግሩ። አድሚን ከሆኑ እና የይለፍ ቃል ከረሱ ከቴክኒክ ቡድን የደህንነት መመለሻ ቁልፍ ይጠይቁ።',
    pendingOfflineActions: 'የተጠባበቁ ከመስመር ውጭ ተግባራት',
    pendingOfflineDetails: 'የተጠባበቁ ከመስመር ውጭ ተግባራት አሉዎት። መስመር ሲገኝ ለማስማማት ወደ አድሚን ይላካሉ።',
    cancel: 'ሰርዝ',
    logoutAnyway: 'ሆኖም ውጣ',
    fillAllRecoveryFields: 'ሁሉንም የመመለሻ መረጃዎች ይሙሉ።',
    passwordMismatch: 'አዲስ የይለፍ ቃል እና ማረጋገጫ አይመሳሰሉም።',
    adminPasswordResetSuccess: 'የአድሚን የይለፍ ቃል ተቀይሯል። አሁን መግባት ይችላሉ።',
    recoveryDisabled: 'በዚህ ሰርቨር መመለሻ ተሰናክሏል። ባለቤቱ ADMIN_RECOVERY_KEY እንዲያቀናብር ይጠይቁ።',
    hideArchived: 'የታሸጉ ደብቅ',
    seeArchivedProducts: 'የታሸጉ ምርቶች እይ',
    addProductGroup: 'የምርት ቡድን ጨምር',
    searchProducts: 'ምርቶችን ፈልግ',
    searchGroupsOrVariants: 'ቡድኖችን ወይም ቫሪያንቶችን ፈልግ...',
    addCategory: 'ምድብ ጨምር',
    categoryAdded: 'ምድብ ታክሏል።',
    deleteVariantConfirm: 'ይህን ቫሪያንት ልንሰርዝ? መሰረዝ ካልተቻለ ይታሸጋል።',
    passwordPolicyHint: 'የይለፍ ቃል 8+ ፊደላት እና ፊደል፣ ቁጥር፣ ልዩ ምልክት ይኖረው።',
    confirm: 'አረጋግጥ',
    confirmAction: 'ለመቀጠል እርግጠኛ ነዎት?',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  const setLang = (lang) => {
    setLanguage(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const value = useMemo(() => ({ language, setLang, t }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
