import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    appTitle: 'Sina Sweet',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    username: 'Username',
    password: 'Password',
    branch: 'Location',
    dashboard: 'Dashboard',
    products: 'Products Management',
    addProduct: 'Add Product',
    newSale: 'New Sale',
    cartEmpty: 'Cart is empty',
    completeSale: 'Complete Sale',
    queueSaleOffline: 'Queue Sale (Offline)',
    processing: 'Processing...',
    inventory: 'Inventory',
    sales: 'Sales',
    expenses: 'Expenses',
    staffPayments: 'Staff Payments',
    reports: 'Reports',
    notifications: 'Notifications',
    syncQueue: 'Sync Queue',
    staffManagement: 'Staff Management',
    historyLifecycle: 'History Lifecycle',
    batches: 'Batches',
    logout: 'Logout',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    salesHistory: 'Sales History',
    startDate: 'Start Date',
    endDate: 'End Date',
    specificDayExact: 'Specific Day (exact)',
    search: 'Search',
    receiptOrAmount: 'Receipt # or Amount',
    receipt: 'Receipt #',
    dateTime: 'Date & Time',
    amount: 'Amount',
    cashier: 'Cashier',
    payment: 'Payment',
    status: 'Status',
    voidDetails: 'Void Details',
    sync: 'Sync',
    actions: 'Actions',
    noSalesFound: 'No sales found',
    unknown: 'Unknown',
    cancelled: 'Cancelled',
    completed: 'Completed',
    noReasonProvided: 'No reason provided',
    offline: 'Offline',
    online: 'Online',
    view: 'View',
    void: 'Void',
    transactionInfo: 'Transaction Info',
    items: 'Items',
    product: 'Product',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    voidThisSale: 'Void This Sale?',
    reasonForVoiding: 'Reason for voiding *',
    close: 'Close',
    processFailedLoadSalesHistory: 'Failed to load sales history',
    provideVoidReason: 'Please provide a reason for voiding this sale',
    failedVoidSale: 'Failed to void sale',
    processingShort: 'Processing...',
    voidSaleRestoreInventory: 'Void Sale & Restore Inventory',
    voidRemainingSuffix: 'to void',
    reasonPlaceholder: 'e.g., Customer changed their mind, entered wrong amount...',
    voided: 'VOIDED',
    paymentMethod: 'Payment Method',
    dateAndTimeLabel: 'Date & Time:',
    amountLabel: 'Amount:',
    cashierLabel: 'Cashier:',
    paymentMethodLabel: 'Payment Method:',
    voidedAt: 'Voided at:',
    reason: 'Reason:',
    inventoryRestoredMessage: 'Inventory will be restored automatically.',
    remainingToVoidPrefix: 'You have',
    remainingToVoidMiddle: 'minutes remaining to void this sale.',
    saleVoidedMessage: 'has been voided. Inventory restored.',
  },
  am: {
    appTitle: 'ሲና ስዊት',
    signIn: 'ግባ',
    signingIn: 'በመግባት ላይ...',
    username: 'የተጠቃሚ ስም',
    password: 'የይለፍ ቃል',
    branch: 'ቦታ',
    dashboard: 'ዳሽቦርድ',
    products: 'የምርት አስተዳደር',
    addProduct: 'ምርት ጨምር',
    newSale: 'አዲስ ሽያጭ',
    cartEmpty: 'ጋሪው ባዶ ነው',
    completeSale: 'ሽያጭ አጠናቅቅ',
    queueSaleOffline: 'ከመስመር ውጭ ሽያጭ አስቀምጥ',
    processing: 'በሂደት ላይ...',
    inventory: 'ኢንቨንተሪ',
    sales: 'ሽያጭ',
    expenses: 'ወጪዎች',
    staffPayments: 'የሰራተኛ ክፍያ',
    reports: 'ሪፖርቶች',
    notifications: 'ማሳወቂያዎች',
    syncQueue: 'ሲንክ ዝርዝር',
    staffManagement: 'የሰራተኛ አስተዳደር',
    historyLifecycle: 'ታሪክ ላይፍሳይክል',
    batches: 'ባች',
    logout: 'ውጣ',
    language: 'ቋንቋ',
    theme: 'ገጽታ',
    light: 'ብርሃን',
    dark: 'ጨለማ',
    salesHistory: 'የሽያጭ ታሪክ',
    startDate: 'የመጀመሪያ ቀን',
    endDate: 'የመጨረሻ ቀን',
    specificDayExact: 'የተወሰነ ቀን (ትክክለኛ)',
    search: 'ፈልግ',
    receiptOrAmount: 'ደረሰኝ ቁጥር ወይም መጠን',
    receipt: 'ደረሰኝ ቁጥር',
    dateTime: 'ቀን እና ሰዓት',
    amount: 'መጠን',
    cashier: 'ካሸር',
    payment: 'ክፍያ',
    status: 'ሁኔታ',
    voidDetails: 'የመሰረዝ ዝርዝር',
    sync: 'ሲንክ',
    actions: 'እርምጃዎች',
    noSalesFound: 'ምንም ሽያጭ አልተገኘም',
    unknown: 'ያልታወቀ',
    cancelled: 'ተሰርዟል',
    completed: 'ተጠናቋል',
    noReasonProvided: 'ምክንያት አልተሰጠም',
    offline: 'ከመስመር ውጭ',
    online: 'በመስመር ላይ',
    view: 'ይመልከቱ',
    void: 'ሰርዝ',
    transactionInfo: 'የግብይት መረጃ',
    items: 'እቃዎች',
    product: 'ምርት',
    qty: 'ብዛት',
    price: 'ዋጋ',
    total: 'ጠቅላላ',
    voidThisSale: 'ይህን ሽያጭ ሰርዝ?',
    reasonForVoiding: 'የመሰረዝ ምክንያት *',
    close: 'ዝጋ',
    processFailedLoadSalesHistory: 'የሽያጭ ታሪክ መጫን አልተቻለም',
    provideVoidReason: 'እባክዎ ይህን ሽያጭ ለመሰረዝ ምክንያት ያስገቡ',
    failedVoidSale: 'ሽያጩን መሰረዝ አልተቻለም',
    processingShort: 'በሂደት ላይ...',
    voidSaleRestoreInventory: 'ሽያጭ ሰርዝ እና ኢንቨንተሪ መልስ',
    voidRemainingSuffix: 'ለመሰረዝ',
    reasonPlaceholder: 'ምሳሌ፦ ደንበኛው ሀሳቡን ቀይሯል፣ የተሳሳተ መጠን ገብቷል...',
    voided: 'ተሰርዟል',
    paymentMethod: 'የክፍያ ዘዴ',
    dateAndTimeLabel: 'ቀን እና ሰዓት:',
    amountLabel: 'መጠን:',
    cashierLabel: 'ካሸር:',
    paymentMethodLabel: 'የክፍያ ዘዴ:',
    voidedAt: 'የተሰረዘበት ጊዜ:',
    reason: 'ምክንያት:',
    inventoryRestoredMessage: 'ኢንቨንተሪ በራስ-ሰር ይመለሳል።',
    remainingToVoidPrefix: 'እርስዎ አሁንም',
    remainingToVoidMiddle: 'ደቂቃ ቀርቶዎታል ይህን ሽያጭ ለመሰረዝ።',
    saleVoidedMessage: 'ተሰርዟል። ኢንቨንተሪ ተመልሷል።',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  const setLang = (lang) => {
    setLanguage(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const value = useMemo(() => ({ language, setLang, t }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
